[package]
name = "xrd-peak-fit"
version = "0.1.0"
authors = ["nils sabelstrom <nilssab@gmail.com>"]
edition = "2018"
description = "Peak fitting library for 2D XRD data"
readme = "README.md"
repository = "https://github.com/nilssab/xrd-peak-fit/"
license = "MIT"

[dependencies]
